language: node_js
node_js:
    - 12
install:
    - npm install
script:
    - npm run lint:all
    - npm run test
before_deploy:
    - npm run build
deploy:
    provider: npm
    email: NPM_EMAIL
    api_token: NPM_TOKEN
    cleanup: true
    on:
        branch: master
        tags: true
