language: node_js
node_js:
- 12
before_install:
- npm install -g npm@'>=2.13.5'
install:
- npm install
script:
- npm run lint:all
- npm run test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: NPM_EMAIL
  api_key:
    secure: NPM_TOKEN
  on:
    tags: true
    repo: doganozturk/metrics-catalog-js
  skip_cleanup: 'true'
deploy-api_key:
  secure: NPM_TOKEN
