language: node_js
node_js:
    - 12
install:
    - npm install
script:
    - npm run build
    - npm run lint:all
    - npm run test
deploy:
    provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    cleanup: true
    on:
        branch: master
        tags: true
